app = "hiring-tool-backend"

[build]
  image = "" # leave empty to use Dockerfile

[env]
  PORT = "5001"
  # Set other env vars on Fly.io dashboard or via `fly secrets set`

[[services]]
  internal_port = 5001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
